### ISSUE TITLE
Add a sort order for candidates

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-admin#11]
Each candidate should have an editable field called `sort_order` in the admin that lets us define the order we want candidates to appear when there are no votes. 

For example, we may want to order the Republican candidates in Iowa like this before votes come in, especially for widgets where we can only show three candidates at a time:
- Trump
- Cruz
- Rubio

**Comment by wmandrews** [comment]
https://github.com/newsdev/elex-admin/commit/0c208667dccccb9f3e342f7ff9656ab1e7eab846
