### ISSUE TITLE
Add a JavaScript alert before you can call a winner in the admin

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-admin#13]
When you select a winner in the dropdown, we should have an alert that asks something like, "Are you sure you want to call Martin O'Malley the winner of the Iowa Democratic Caucus?"

cc @jeremyjbowers

**Comment by giratikanon** [comment]
Couldn't get the `elex-admin` working to test this, but here's a start: https://github.com/newsdev/elex-admin/compare/racecall?expand=1

**Comment by jeremyjbowers** [comment]
I like this solution. I'll merge this shortly.

**Comment by jeremyjbowers** [comment]
Totally got this at some point. Working in sha a5453ef0e794df6c9ccf2c5e911a8c5fbd9d218e
