### ISSUE TITLE
Should setting a winner increment the AP updated time? 

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-admin#16]
The main issue we'd be trying to solve is that on the frontend, we're not updating results if the load id is older than the previous one.

However, in a situation where either the API or FTP rewinds in a time, and we need to make a a call when our updated time is behind the frontend clients.

So we either need a way to manually update the timestamp to be ahead of the latest timestamp we've ever had, or some other solution (like "force_update" in the API).

**Comment by jeremyjbowers** [comment]
This is solved in IC now where both the timestamp AND the message body are checked for changes.
