### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-admin#17]
- Postgres hstore extension wasn't installed
- Couldn't run `initialize_racedate` because it expected `elex_races` to exist

**Comment by jeremyjbowers** [comment]
These are failures of documentation.
- `hstore` is a requirement but is not documented.
- Running `./scripts/dev/reload.sh` solves the `initialize_racedate.py` conundrum but it is not documented.

**Comment by jeremyjbowers** [comment]
Handling this in #21. Closing as a duplicate.
