### ISSUE TITLE
Production admin displays as "Dev" when there's a status message

### ISSUE THREAD

**Issue by giratikanon** [newsdev/elex-admin#34]
http://int-elex-prd-east.newsdev.net/elections/2016/loader/?message=Process%20DC_WY%7C2016-03-12%7CAPI%20started

![image](https://cloud.githubusercontent.com/assets/333527/13723637/60d2073a-e839-11e5-90ce-249aea4c5102.png)

**Comment by jeremyjbowers** [comment]
Well, that's exciting. I'll figure it out this afternoon. The whole prd/stg/dev coloring happens in JS.

**Comment by jeremyjbowers** [comment]
That was a really great misplaced `}`. Fixed now.
