### ISSUE TITLE
Allow for bulk initialization to accept AP calls 

### ISSUE THREAD

**Issue by wmandrews** [newsdev/elex-admin#36]
For all national races, for all local races, possibly as two different buttons.
![image](https://cloud.githubusercontent.com/assets/126789/14963794/4fb17096-1073-11e6-9120-156c25c8596c.png)

**Comment by rshorey** [comment]
I'm going to make these separate buttons instead of a toggle because with a toggle I'm not sure what to do if someone goes and manually sets a few specific races to be different.
